### PR TITLE
chore: docstring typos

### LINKED ISSUE #254: Fix Typo
**Describe the bug**

I found some typos in docstring and alert.

Can I fix these typos and send pull request?

Hope to hear from you soon！ 

ex) 
image

**What is the current behavior?**
N/A
**If the current behavior is a bug, please provide the steps to reproduce.**

N/A
**Expected behavior**

N/A
**Screenshots**

**Other relevant information:**
N/A
**Additional context**
N/A

### PR DESCRIPTION
**Pull request by mei28**
**What kind of change does this PR introduce?**

fix typos in docstring.

image

**Closing issues**

closes #254

### CODE REVIEW

**Comment by Optimox** [comment]
Thanks @mei28 is this ready to be merged?

**Review by eduardocarvp — APPROVED** [review]

**Comment by mei28** [comment]
This is all the typos I found !
please review them, thank you.

If I find another typos, I'll send another PR.

**Review by Optimox — CHANGES_REQUESTED** [review]
Great work thank you!
Could you please squash this into one single commit? Then we can merge.

**Comment by mei28** [comment]
The commits are squashed into one.
Is this okay?

**Review by Optimox — APPROVED** [review]
It's perfect, thank you very much!

**Pull request merged**
