### PR TITLE
Added conda install instruction

### LINKED ISSUE #346: Add a `conda` install option for `pytorch-tabnet`
## Feature request

A `conda` installation option could be quite helpful as an alternative alongside the ability to install `pytorch-tabnet` with `pip`. I have already done the work necessary to make `pytorch-tabnet` available on `conda-forge`. (PR: https://github.com/conda-forge/staged-recipes/pull/17292)

Now you can install `pytorch-tabnet` as:

```sh
conda install -c conda-forge pytorch-tabnet
```

> Note: the PR was just merged. Give it some 2-3 hours and it will be ready for use.

:bulb: **I will send a PR to update the docs/readme.**

### PR DESCRIPTION
**Pull request by sugatoray**
This closes #346. My other PR with conda-forge put `pytorch-tabnet` on `conda-forge` channel. Please see issue #346 for more details. 

This PR updated the readme file with:

- [x] conda install instruction
- [x] relevant badges

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

**What kind of change does this PR introduce?**

**Does this PR introduce a breaking change?**

**What needs to be documented once your changes are merged?** `NA`

**Closing issues**

closes #346

### CODE REVIEW

**Comment by sugatoray** [comment]
cc: @Hartorn @Optimox

**Comment by Hartorn** [comment]
@sugatoray Is there anything to do for us to maintain this ?

**Comment by Hartorn** [comment]
@sugatoray could you reword your commit message using this : https://www.conventionalcommits.org/en/v1.0.0-beta.2/ ?
Else everything looks great :)

**Comment by sugatoray** [comment]
@Hartorn Do you mean change the push with a new commit message such as the following (or change the previous commit message with something like the following)?

```
feat: updated readme with conda-install-instruction

- added conda install instruction
- added relevant badges
```

Should I use `feat` or `docs`?

**Comment by Hartorn** [comment]
> @Hartorn Do you mean push with a _new commit message_ such as the following (or change the previous commit message with something like the following)?
> 
> ```
> feat: added conda install option
> 
> updated readme with conda-install-instruction
> - added conda install instruction
> - added relevant badges
> 
> Closes issue #346 
> ```
> 
> Should I use `feat` or `docs`?

I mean amending you current commit, and pushing again, with commit message as you just wrote

use feat

**Comment by sugatoray** [comment]
> I mean amending you current commit, and pushing again, with commit message as you just wrote
> 
> use feat

Done.

cc: @Hartorn

**Review by Optimox — APPROVED** [review]
Looks good to me! Thanks again!

**Pull request merged**
