### PR TITLE
chore: update example notebooks

### PR DESCRIPTION
**Pull request by ddofer**
Updated census, regression notebooks. Proper variable names, better examples of categorical embedding dimensionality picking, added display of global feature importance, and column feature names. Also corrected incorrect score names in regression (output is MSE, not roc). 
Additionally, notebooks now include output of running them, making them much easier to view as examples online.

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

**Closing issues**

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by ddofer** [comment]
I didn't experiment with embedding sizes (in fact, embedding size of 2 for the gender [cardinality 2] makes no sense), I don't mind making it use logn. The key is just to show a simple heuristic for users, as opposed to a vector of magic numbers. 
I'll try to rename it - you just need the branch name changed?

**Comment by ddofer** [comment]
I'm on a backup computer that lacks github setup, so renaming the branch is a bit of a hassle. I can do so if important?

**Comment by frankherfert** [comment]
I recently started to improve the example notebooks before this issue was created.
Some of the parts have an overlap with what @ddofer did, like function for getting embedding sizes.

Have a look at #162 to see which parts we could use from both.

**Comment by ddofer** [comment]
Could you please clarify what changes should be made prior to acceptance? Do you want this merged with #162? (That's a different contributor..)

**Comment by Optimox** [comment]
@ddofer I'm ok with merging this, changes needed are name of the commit to something like `chore: update example notebooks` in order to have release report working properly.

**Comment by ddofer** [comment]
> @ddofer I'm ok with merging this, changes needed are name of the commit to something like `chore: update example notebooks` in order to have release report working properly.

Changed - is it ok now?

**Comment by Optimox** [comment]
> > @ddofer I'm ok with merging this, changes needed are name of the commit to something like `chore: update example notebooks` in order to have release report working properly.
> 
> Changed - is it ok now?

Did you change the name of the commit? or just the name of the PR? Cause the problem is the name of the commit iself.

**Comment by Optimox** [comment]
@ddofer could you change the commit name so that I can merge this?

**Comment by Optimox** [comment]
These are out of date now.

It would probably be easier to open a new PR to try to improve upon existing notebook examples.

**Pull request closed without merging**
